/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-08-05 07:48:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.myblog;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>mypage</title>\r\n");
      out.write("    <!-- Favicon-->\r\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\" />\r\n");
      out.write("    <!-- Font Awesome icons (free version)-->\r\n");
      out.write("    <script src=\"https://use.fontawesome.com/releases/v5.13.0/js/all.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- Google fonts-->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Indie+Flower&family=Nanum+Pen+Script&family=Noto+Sans+KR:wght@500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <!--AOS 라이브러리-->\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"https://unpkg.com/aos@2.3.1/dist/aos.css\" />\r\n");
      out.write("     <!--hover.css-->\r\n");
      out.write("     <link href=\"../css/hover.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("    <link href=\"../css/styles1.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- CSS only -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\" integrity=\"sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- JS, Popper.js, and jQuery -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\" integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\" integrity=\"sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <header>\r\n");
      out.write("      <nav class=\"navBar\">\r\n");
      out.write("       \t네비게이션 바\r\n");
      out.write("      </nav>\r\n");
      out.write("      <div class=\"backgroundImg\">\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"layer\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div class=\"profileImg_wrapper\">\r\n");
      out.write("      <div class=\"profileCircle\">\r\n");
      out.write("        <div class=\"userProfile\">\r\n");
      out.write("          <img class=\"userProfileImg\" src=\"../image/harin.jpg\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"userId\">\r\n");
      out.write("        UserId_120329\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  <!--content -->\r\n");
      out.write("  <input type=\"hidden\" id=\"pg\" value=\"1\">\r\n");
      out.write("  <div class=\"content\">\r\n");
      out.write("    <div class=\"content_wrapper\">\r\n");
      out.write("      <div class=\"myInfo_wrapper\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"follow_wrapper\">\r\n");
      out.write("          <div class=\"follower\">\r\n");
      out.write("            <div class=\" numberDiv\">87</div>\r\n");
      out.write("            팔로우\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"following\" >\r\n");
      out.write("            <div class=\" numberDiv\">102</div>\r\n");
      out.write("            팔로잉\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"listCount\">\r\n");
      out.write("            <div class=\" numberDiv\">102</div>\r\n");
      out.write("            <p>게시물</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-outline-secondary\" id=\"writeOptionBtn\" style=\"font-size:9px; border-radius:20px; width:100px;\">글 작성</button>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-outline-secondary\" style=\"font-size:9px; border-radius:20px; width:100px;\">회원정보수정</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"myBlog_wrapper\">\r\n");
      out.write("        <table id=\"tableHeadder\">\r\n");
      out.write("          <th>\r\n");
      out.write("            <td style=\"font-size:9px; border-top:2px solid; font-weight:bold; width:8%; height:30px;\">여행기</td>\r\n");
      out.write("            <td style=\"border-top: 1px solid; width:92%;\"></td>\r\n");
      out.write("          </th>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"myblogList\" data-aos=\"fade-up\" data-aos-duration=\"3000\">\r\n");
      out.write("          <!--첫번째 리스트-->\r\n");
      out.write("          <div id=\"myblog_feed\" class=\"hvr-grow-shadow\">\r\n");
      out.write("            <div class=\"myblog_img\">\r\n");
      out.write("              <img class=\"listImg\"src=\"../image/architecture.jpg\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"myblog_info\">\r\n");
      out.write("              <div class=\"myblog_subject\">\r\n");
      out.write("                Lorem ipsum dolor sit amet, consectetur\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"myblog_content\">\r\n");
      out.write("                Lorem ipsum dolor sit amet, consectetur adipiscing elit, Lorem ipsum dolor sit amet, consectetur adipiscing elit.\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"myblog_userFunction\">\r\n");
      out.write("                <div class=\"like\">\r\n");
      out.write("                  <i class=\"far fa-heart\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"reply\">\r\n");
      out.write("                  <i class=\"fas fa-comment-dots\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"myblog_travleDay\">\r\n");
      out.write("                  20.06.03~20.06.08\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!--두번째 리스트-->\r\n");
      out.write("          <div id=\"myblog_feed\" class=\"hvr-grow-shadow\">\r\n");
      out.write("            <div class=\"myblog_img\">\r\n");
      out.write("              <img class=\"listImg\"src=\"../image/gyungju.jpg\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"myblog_info\">\r\n");
      out.write("              <div class=\"myblog_subject\">\r\n");
      out.write("                Lorem ipsum dolor sit amet, consectetur adipiscing elit.\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"myblog_content\">\r\n");
      out.write("                Lorem ipsum dolor sit amet, consectetur adipiscing elit, Lorem ipsum dolor sit amet, consectetur adipiscing elit.\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"myblog_userFunction\">\r\n");
      out.write("                <div class=\"like\">\r\n");
      out.write("                  <i class=\"far fa-heart\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"reply\">\r\n");
      out.write("                  <i class=\"fas fa-comment-dots\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"myblog_travleDay\">\r\n");
      out.write("                  20.06.03~20.06.08\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!--세번쨰 리스트-->\r\n");
      out.write("          <div id=\"myblog_feed\" class=\"hvr-grow-shadow\">\r\n");
      out.write("            <div class=\"myblog_img\">\r\n");
      out.write("              <img class=\"listImg\"src=\"../image/game.png\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"myblog_info\">\r\n");
      out.write("              <div class=\"myblog_subject\">\r\n");
      out.write("                Lorem ipsum dolor sit amet, consectetur adipiscing elit.\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"myblog_content\">\r\n");
      out.write("                Lorem ipsum dolor sit amet, consectetur adipiscing elit, Lorem ipsum dolor sit amet, consectetur adipiscing elit.\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"myblog_userFunction\">\r\n");
      out.write("                <div class=\"like\">\r\n");
      out.write("                  <i class=\"far fa-heart\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"reply\">\r\n");
      out.write("                  <i class=\"fas fa-comment-dots\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"myblog_travleDay\">\r\n");
      out.write("                  20.06.03~20.06.08\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("    <footer>\r\n");
      out.write("    </footer>\r\n");
      out.write("  </body>\r\n");
      out.write("  <!---->\r\n");
      out.write("  <!------------- Modal --------------->\r\n");
      out.write("  <div class=\"modal fade\" id=\"followModal\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal content-->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <h4 class=\"modal-title\"></h4>\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("          <table class=\"modal_table\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td style=\"width:70px;\"><img id=\"modal_userImg\"src=\"../image/paris.jpg\"></td>\r\n");
      out.write("              <td id=\"modal_userID\">USER_ID</td>\r\n");
      out.write("              <td id=\"modal_userFollow\"><buttton class=\"btn btn-outline-primary\">팔로우</button></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td style=\"width:70px;\"><img id=\"modal_userImg\"src=\"../image/circus.png\"></td>\r\n");
      out.write("              <td id=\"modal_userID\">USER_ID</td>\r\n");
      out.write("              <td id=\"modal_userFollow\"><buttton class=\"btn btn-outline-primary\">팔로우</button></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td style=\"width:70px;\"><img id=\"modal_userImg\"src=\"../image/safe.png\"></td>\r\n");
      out.write("              <td id=\"modal_userID\">USER_ID</td>\r\n");
      out.write("              <td id=\"modal_userFollow\"><buttton class=\"btn btn-outline-primary\">팔로우</button></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td style=\"width:70px;\"><img id=\"modal_userImg\"src=\"../image/user.png\"></td>\r\n");
      out.write("              <td id=\"modal_userID\">USER_ID</td>\r\n");
      out.write("              <td id=\"modal_userFollow\"><buttton class=\"btn btn-outline-primary\">팔로우</button></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td style=\"width:70px;\"><img id=\"modal_userImg\"src=\"../image/cake.png\"></td>\r\n");
      out.write("              <td id=\"modal_userID\">USER_ID</td>\r\n");
      out.write("              <td id=\"modal_userFollow\"><buttton class=\"btn btn-outline-primary\">팔로우</button></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td style=\"width:70px;\"><img id=\"modal_userImg\"src=\"../image/paris.jpg\"></td>\r\n");
      out.write("              <td id=\"modal_userID\">USER_ID</td>\r\n");
      out.write("              <td id=\"modal_userFollow\"><buttton class=\"btn btn-outline-primary\">팔로우</button></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"count\" value=\"1\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("   <!-- 글작성 BTN -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"writeOptionModal\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <!-- Modal content-->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("        \t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\r\n");
      out.write("        \t<div class=\"bodyHeader\">새로 만들기</div>\r\n");
      out.write("\t\t\t<div class=\"writeOptionWrapper\">\r\n");
      out.write("\t\t\t\t<div class=\"travelsWriteWrapper\">\r\n");
      out.write("\t\t\t\t\t<div id=\"travelsWriteImg\" class=\"hvr-grow-shadow\"><i id=\"writeOptionImg\" class=\"fas fa-suitcase\" ></i></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"optionContentWrapper\">\r\n");
      out.write("\t\t\t\t\t\t<h5>여행기</h5>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"optionText\">여행 기록을 코스별, 일정별로 깔끔하게 기록해보세요.</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"writeBlogWrapper\">\r\n");
      out.write("\t\t\t\t\t<div id=\"writeBlogImg\" class=\"hvr-grow-shadow\"><i id=\"writeOptionImg\" class=\"far fa-edit\"></i></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"optionContentWrapper\">\r\n");
      out.write("\t\t\t\t\t\t<h5>M에세이</h5>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"optionText\">여행을 자유롭게 나만의 에세이로 기록해보세요.</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"count\" value=\"1\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Bootstrap core JS-->\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <!-- Third party plugin JS-->\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js\"></script>\r\n");
      out.write("  <!-- Contact form JS-->\r\n");
      out.write("  <script src=\"assets/mail/jqBootstrapValidation.js\"></script>\r\n");
      out.write("  <script src=\"assets/mail/contact_me.js\"></script>\r\n");
      out.write("  <!--AOS 라이브러리-->\r\n");
      out.write("  <script src=\"https://unpkg.com/aos@2.3.1/dist/aos.js\"></script>\r\n");
      out.write("  <!-- Core theme JS-->\r\n");
      out.write("  <script src=\"../js/scripts.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("      AOS.init({\r\n");
      out.write("          easing: 'ease-out-back',\r\n");
      out.write("          duration: 1000\r\n");
      out.write("      });\r\n");
      out.write("  </script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
