/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-08-05 11:23:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.blog;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class blogList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../css/blogList.css\">\r\n");
      out.write("  <script src=\"https://kit.fontawesome.com/75c3f69c14.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" <br><br>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("  <div class=\"morip_banner_slider\">\r\n");
      out.write("  \t<div class=\"img img0\">\r\n");
      out.write("  \t  <div class=\"content\">전체</div>\r\n");
      out.write("      <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \r\n");
      out.write("\t<div class=\"img img1\">\r\n");
      out.write("  \t  <div class=\"content\">서울</div>\r\n");
      out.write("      <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \r\n");
      out.write("  \t<div class=\"img img2\">\r\n");
      out.write("  \t  <div class=\"content\">부산</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img3\">\r\n");
      out.write("  \t  <div class=\"content\">대구</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img4\">\r\n");
      out.write("  \t  <div class=\"content\">인천</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img5\">\r\n");
      out.write("  \t  <div class=\"content\">광주</div>\r\n");
      out.write("      <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \r\n");
      out.write("  \t<div class=\"img img6\">\r\n");
      out.write("  \t  <div class=\"content\">대전</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img7\">\r\n");
      out.write("  \t  <div class=\"content\">울산</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img8\">\r\n");
      out.write("  \t  <div class=\"content\">강원도</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img9\">\r\n");
      out.write("  \t  <div class=\"content\">경기도</div>\r\n");
      out.write("      <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \r\n");
      out.write("  \t<div class=\"img img10\">\r\n");
      out.write("  \t  <div class=\"content\">충북</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img11\">\r\n");
      out.write("  \t  <div class=\"content\">충남</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img12\">\r\n");
      out.write("  \t  <div class=\"content\">전북</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img13\">\r\n");
      out.write("  \t  <div class=\"content\">전남</div>\r\n");
      out.write("      <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \r\n");
      out.write("  \t<div class=\"img img14\">\r\n");
      out.write("  \t  <div class=\"content\">경북</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img15\">\r\n");
      out.write("  \t  <div class=\"content\">경남</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img16\">\r\n");
      out.write("  \t  <div class=\"content\">제주도</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  </div>  \r\n");
      out.write("  <!-- 리스트 보여주기 -->\r\n");
      out.write("  <!-- \r\n");
      out.write("        <div class=\"myBlog_wrapper\">\r\n");
      out.write("        <table id=\"tableHeadder\">\r\n");
      out.write("          <th>\r\n");
      out.write("            <td style=\"font-size:9px; border-top:2px solid; font-weight:bold; width:8%; height:30px;\">여행기</td>\r\n");
      out.write("            <td style=\"border-top: 1px solid; width:92%;\"></td>\r\n");
      out.write("          </th>\r\n");
      out.write("        </table> -->\r\n");
      out.write("       <!--  <div class=\"myblogList\" data-aos=\"fade-up\" data-aos-duration=\"3000\">\r\n");
      out.write("          첫번째 리스트\r\n");
      out.write("          <div id=\"myblog_feed\" class=\"hvr-grow-shadow\">\r\n");
      out.write("            <div class=\"myblog_img\">\r\n");
      out.write("              <img class=\"listImg\"src=\"../image/testimg.png\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"myblog_info\">\r\n");
      out.write("              <div class=\"myblog_subject\">\r\n");
      out.write("                Lorem ipsum dolor sit amet, consectetur\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"myblog_content\">\r\n");
      out.write("                Lorem ipsum dolor sit amet, consectetur adipiscing elit, Lorem ipsum dolor sit amet, consectetur adipiscing elit.\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"myblog_userFunction\">\r\n");
      out.write("                <div class=\"like\">\r\n");
      out.write("                  <i class=\"far fa-heart\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"reply\">\r\n");
      out.write("                  <i class=\"fas fa-comment-dots\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"myblog_travleDay\">\r\n");
      out.write("                  20.06.03~20.06.08\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("       -->\r\n");
      out.write("       <div class=\"writeBlog\">\r\n");
      out.write("         <span class=\"write_text\">여행기</span>\r\n");
      out.write("         <button class=\"snip1535\">Submit</button>\r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("      <!-- 리스트 보여주기 기환 버젼 -->\r\n");
      out.write("\t<div class=\"blogList_wrapper\">\r\n");
      out.write("\t  <!-- 리스트1 -->\r\n");
      out.write("\t  <div id=\"blogList_feed\" class=\"hvr-grow-shadow\">\r\n");
      out.write("\t    <div class=\"blogList_img\">\r\n");
      out.write("\t\t  <img class=\"listImg\"src=\"../image/testimg.png\" alt=\"\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"blogList_info\">\r\n");
      out.write("\t\t  <div class=\"blogList_subject\">\r\n");
      out.write("\t\t\tLorem ipsum dolor sit amet, consectetur\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"blogList_content\">\r\n");
      out.write("\t\t\tLorem ipsum dolor sit amet, consectetur adipiscing elit, Lorem ipsum dolor sit amet, consectetur adipiscing elit.\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"blogList_userFunction\">\r\n");
      out.write("\t\t    <div class=\"like\">\r\n");
      out.write("              <i class=\"far fa-heart\"></i>\r\n");
      out.write("              <span class=\"like_count\"> 100</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"reply\">\r\n");
      out.write("              <i class=\"fas fa-comment-dots\"></i>\r\n");
      out.write("              <span class=\"reply_count\"> 301</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span class=\"blogList_travleDay\">\r\n");
      out.write("              20.06.03~20.06.08\r\n");
      out.write("            </span>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <!-- 리스트1 -->\r\n");
      out.write("\t  <div id=\"blogList_feed\" class=\"hvr-grow-shadow\">\r\n");
      out.write("\t    <div class=\"blogList_img\">\r\n");
      out.write("\t\t  <img class=\"listImg\"src=\"../image/testimg.png\" alt=\"\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"blogList_info\">\r\n");
      out.write("\t\t  <div class=\"blogList_subject\">\r\n");
      out.write("\t\t\tLorem ipsum dolor sit amet, consectetur\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"blogList_content\">\r\n");
      out.write("\t\t\tLorem ipsum dolor sit amet, consectetur adipiscing elit, Lorem ipsum dolor sit amet, consectetur adipiscing elit.\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"blogList_userFunction\">\r\n");
      out.write("\t\t    <div class=\"like\">\r\n");
      out.write("              <i class=\"far fa-heart\"></i>\r\n");
      out.write("              <span class=\"like_count\"> 100</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"reply\">\r\n");
      out.write("              <i class=\"fas fa-comment-dots\"></i>\r\n");
      out.write("              <span class=\"reply_count\"> 301</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span class=\"blogList_travleDay\">\r\n");
      out.write("              20.06.03~20.06.08\r\n");
      out.write("            </span>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <!-- 리스트1 -->\r\n");
      out.write("\t  <div id=\"blogList_feed\" class=\"hvr-grow-shadow\">\r\n");
      out.write("\t    <div class=\"blogList_img\">\r\n");
      out.write("\t\t  <img class=\"listImg\"src=\"../image/testimg.png\" alt=\"\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"blogList_info\">\r\n");
      out.write("\t\t  <div class=\"blogList_subject\">\r\n");
      out.write("\t\t\tLorem ipsum dolor sit amet, consectetur\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"blogList_content\">\r\n");
      out.write("\t\t\tLorem ipsum dolor sit amet, consectetur adipiscing elit, Lorem ipsum dolor sit amet, consectetur adipiscing elit.\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"blogList_userFunction\">\r\n");
      out.write("\t\t    <div class=\"like\">\r\n");
      out.write("              <i class=\"far fa-heart\"></i>\r\n");
      out.write("              <span class=\"like_count\"> 100</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"reply\">\r\n");
      out.write("              <i class=\"fas fa-comment-dots\"></i>\r\n");
      out.write("              <span class=\"reply_count\"> 301</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span class=\"blogList_travleDay\">\r\n");
      out.write("              20.06.03~20.06.08\r\n");
      out.write("            </span>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <!-- 리스트1 -->\r\n");
      out.write("\t  <div id=\"blogList_feed\" class=\"hvr-grow-shadow\">\r\n");
      out.write("\t    <div class=\"blogList_img\">\r\n");
      out.write("\t\t  <img class=\"listImg\"src=\"../image/testimg.png\" alt=\"\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"blogList_info\">\r\n");
      out.write("\t\t  <div class=\"blogList_subject\">\r\n");
      out.write("\t\t\tLorem ipsum dolor sit amet, consectetur\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"blogList_content\">\r\n");
      out.write("\t\t\tLorem ipsum dolor sit amet, consectetur adipiscing elit, Lorem ipsum dolor sit amet, consectetur adipiscing elit.\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"blogList_userFunction\">\r\n");
      out.write("\t\t    <div class=\"like\">\r\n");
      out.write("              <i class=\"far fa-heart\"></i>\r\n");
      out.write("              <span class=\"like_count\"> 100</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"reply\">\r\n");
      out.write("              <i class=\"fas fa-comment-dots\"></i>\r\n");
      out.write("              <span class=\"reply_count\"> 301</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span class=\"blogList_travleDay\">\r\n");
      out.write("              20.06.03~20.06.08\r\n");
      out.write("            </span>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t</div>\r\n");
      out.write("      <br><br><br><br>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("  \r\n");
      out.write("<!--   \r\n");
      out.write("  리스트 보여주기 ajax\r\n");
      out.write("        <div class=\"myBlog_wrapper\">\r\n");
      out.write("        <table id=\"tableHeadder\">\r\n");
      out.write("          <th>\r\n");
      out.write("            <td style=\"font-size:9px; border-top:2px solid; font-weight:bold; width:8%; height:30px;\">여행기</td>\r\n");
      out.write("            <td style=\"border-top: 1px solid; width:92%;\"></td>\r\n");
      out.write("          </th>\r\n");
      out.write("        </table>\r\n");
      out.write("      </div>\r\n");
      out.write("</body> -->\r\n");
      out.write("\r\n");
      out.write("<!-- JQuery  -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<!-- Slick Carousel -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\t\t\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/main.js\" ></script>\t\t\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/blog.js\" ></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
