/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-08-05 07:11:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.template;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../css/main.css\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Roboto:ital,wght@1,400&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"https://kit.fontawesome.com/75c3f69c14.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Poppins:ital@1&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Gothic+A1:wght@300&family=Indie+Flower&family=Jua&family=Noto+Sans+KR&family=Poppins:wght@200&family=Roboto:wght@300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"morip_main\">\r\n");
      out.write("\r\n");
      out.write("  <!-- morip info\r\n");
      out.write("  <div class=\"morip_introduce\">\t\r\n");
      out.write("    \r\n");
      out.write("    <pre class=\"morip_text\">\r\n");
      out.write("      안녕하세요.<span >\r\n");
      out.write("      MORIP</span>입니다.\r\n");
      out.write("    </pre>\r\n");
      out.write("    <pre class=\"morip_description\">\r\n");
      out.write("      \"행복했던 여행의 모든 순간들,\r\n");
      out.write("       그 간직하고 싶은 기억들을 MORIP에 기록하세요.\r\n");
      out.write("       MORIP이 그 소중한 순간들을 평생 간직해드립니다.\"\r\n");
      out.write("    </pre>\t\r\n");
      out.write("    <br>\r\n");
      out.write("  </div> -->\r\n");
      out.write("  <br><br>\r\n");
      out.write("  \r\n");
      out.write("  <!-- morip banner -->\r\n");
      out.write("  <div class=\"morip_banner\"></div>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  \r\n");
      out.write("  <!-- morip slider -->\r\n");
      out.write(" <!--  <i class=\"fas fa-chevron-left prev\"></i>\r\n");
      out.write("  <i class=\"fas fa-chevron-right next\"></i> -->\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"morip_banner_slider\">\r\n");
      out.write("  \t<div class=\"img img0\">\r\n");
      out.write("  \t  <div class=\"content\">전체</div>\r\n");
      out.write("      <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \r\n");
      out.write("\t<div class=\"img img1\">\r\n");
      out.write("  \t  <div class=\"content\">서울</div>\r\n");
      out.write("      <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \r\n");
      out.write("  \t<div class=\"img img2\">\r\n");
      out.write("  \t  <div class=\"content\">부산</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img3\">\r\n");
      out.write("  \t  <div class=\"content\">대구</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img4\">\r\n");
      out.write("  \t  <div class=\"content\">인천</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img5\">\r\n");
      out.write("  \t  <div class=\"content\">광주</div>\r\n");
      out.write("      <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \r\n");
      out.write("  \t<div class=\"img img6\">\r\n");
      out.write("  \t  <div class=\"content\">대전</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img7\">\r\n");
      out.write("  \t  <div class=\"content\">울산</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img8\">\r\n");
      out.write("  \t  <div class=\"content\">강원도</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img9\">\r\n");
      out.write("  \t  <div class=\"content\">경기도</div>\r\n");
      out.write("      <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \r\n");
      out.write("  \t<div class=\"img img10\">\r\n");
      out.write("  \t  <div class=\"content\">충북</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img11\">\r\n");
      out.write("  \t  <div class=\"content\">충남</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img12\">\r\n");
      out.write("  \t  <div class=\"content\">전북</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img13\">\r\n");
      out.write("  \t  <div class=\"content\">전남</div>\r\n");
      out.write("      <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \r\n");
      out.write("  \t<div class=\"img img14\">\r\n");
      out.write("  \t  <div class=\"content\">경북</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img15\">\r\n");
      out.write("  \t  <div class=\"content\">경남</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class=\"img img16\">\r\n");
      out.write("  \t  <div class=\"content\">제주도</div>\r\n");
      out.write("  \t  <div class=\"img-cover\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  </div>  \r\n");
      out.write("  <br>\r\n");
      out.write("  \r\n");
      out.write("  <!-- morip bestBlog -->\r\n");
      out.write("  <div class=\"morip_bestBlog\">\r\n");
      out.write("  \t<h2>이런 여행은 어떠세요?</h2>\r\n");
      out.write("    <h3><span>BEST</span> 여행작가</h3>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"morip_bestBlogWriter\">\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"writer_info\">  \r\n");
      out.write("      \t<div class=\"profile_bg\">\r\n");
      out.write("      \t  <div class=\"profile_image\" style=\"background-image: url('../image/test.jpg')\";></div>\r\n");
      out.write("      \t</div>\r\n");
      out.write("      \t<div class=\"profile_detail\">\r\n");
      out.write("      \t  <p class=\"profile_name\">순수쟁이 기환</p>\r\n");
      out.write("      \t  <p class=\"description\"></p>\r\n");
      out.write("      \t  <div>\r\n");
      out.write("      \t    <div>\r\n");
      out.write("      \t      <button class=\"follow_button\">\r\n");
      out.write("      \t      \t<span>+ 팔로우</span>\r\n");
      out.write("      \t      </button>\r\n");
      out.write("      \t    </div>\r\n");
      out.write("      \t  </div>\r\n");
      out.write("      \t  <div class=\"link_wrapper\">\r\n");
      out.write("      \t    <a href=\"\" class=\"blog_link\">더 많은 여행기 보기 ></a>\r\n");
      out.write("      \t  </div>\r\n");
      out.write("      \t</div>    \t\r\n");
      out.write("      </div>      \r\n");
      out.write("      <div class=\"writer_post\">\r\n");
      out.write("      \t<div class=\"post\">\r\n");
      out.write("      \t  <div class=\"post_image\" style=\"background-image: url('../image/testimg.png')\">\r\n");
      out.write("      \t    <div class=\"post_image_like\">\r\n");
      out.write("      \t      <span class=\"post_image_like_text\">115</span>\r\n");
      out.write("      \t    </div>\r\n");
      out.write("      \t  </div>\r\n");
      out.write("      \t  <div class=\"post_text\"> \r\n");
      out.write("\t        <div class=\"post_title\">\r\n");
      out.write("\t          <p class=\"post_title_p\">제주도 5박6일정도만 여유 있게 즐기기~ 오똔데?</p>\r\n");
      out.write("\t        </div>\t          \r\n");
      out.write("\t      \t<div class=\"post_content\">\r\n");
      out.write("\t\t\t  <p class=\"post_content_p\">\r\n");
      out.write("\t\t\t\t왜 이렇게 사는게 힘들기만 한지\r\n");
      out.write("\t\t\t\t누가 인생이 아름답다고 말한건지\r\n");
      out.write("\t\t\t\t태어났을 떄부터 삶이 내게 준건\r\n");
      out.write("\t\t\t\t끝없이 이겨내야 했던 고난들 뿐인걸\r\n");
      out.write("\t\t\t\t그럴떄마다 나는 거울 속에 나 에게 물어봤지\r\n");
      out.write("\t\t\t\t뭘 잘못했지 도대체 내가 뭘 잘못했길래\r\n");
      out.write("\t\t\t\t내게만 이래 이제 달라질것같지 않아\r\n");
      out.write("\t\t\t\t매일 또그래\r\n");
      out.write("\t\t\t\t하지만 그러면 안되 주저 앉으면 안되\r\n");
      out.write("\t\t\t\t세상이 주는대로 그저 주어진 대로\r\n");
      out.write("\t\t\t\t이렇게 불공평한 세상이 주는대로\r\n");
      out.write("\t\t\t\t그저 받기만 하면\r\n");
      out.write("\t\t\t\t모든 것은 그대로\r\n");
      out.write("\t\t\t\t싸울텐가 포기할텐가\r\n");
      out.write("\t\t\t\t주어진 운명 앞에 굴복하고 말텐가\r\n");
      out.write("\t\t\t\t세상앞에 고개 숙이지 마라\r\n");
      out.write("\t\t\t\t기죽지 마라 그리고 우릴 봐라\r\n");
      out.write("\t      \t  </p>\r\n");
      out.write("\t      \t</div>\r\n");
      out.write("      \t  </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"post\">\r\n");
      out.write("          <div class=\"post_image\"></div>\r\n");
      out.write("      \t  <div class=\"post_text\">\r\n");
      out.write("\t        <div class=\"post_title\"></div>\r\n");
      out.write("\t      \t<div class=\"post_content\"></div>\r\n");
      out.write("      \t  </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"post\">\r\n");
      out.write("          <div class=\"post_image\"></div>\r\n");
      out.write("      \t  <div class=\"post_text\">\r\n");
      out.write("\t        <div class=\"post_title\"></div>\r\n");
      out.write("\t      \t<div class=\"post_content\"></div>\r\n");
      out.write("      \t  </div>\r\n");
      out.write("        </div>        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div> \r\n");
      out.write("   <br><br>\r\n");
      out.write("  \r\n");
      out.write("   \r\n");
      out.write("  <div class=\"text1\">\r\n");
      out.write("  \t<h2>배고프신가요?? 이런음식은 어떠세요?</h2>\r\n");
      out.write("    <h3><span>Top3</span> 맛집!</h3>\r\n");
      out.write("  </div> \r\n");
      out.write("  <!-- 맛집 -->\r\n");
      out.write("  <div class=\"bestFood_post\">\r\n");
      out.write("  \t<div class=\"food_post_bg_image\">\r\n");
      out.write("  \t <div class=\"food_post\">\r\n");
      out.write("  \t   <div class=\"food_post_name\">원조수구레</div>\r\n");
      out.write("  \t   <div class=\"food_post_image\" style=\"background-image: url('../image/foodtest.jpg')\"></div>\r\n");
      out.write("  \t   <div class=\"food_post_contents\">\r\n");
      out.write("  \t     <div class=\"content1\">\r\n");
      out.write("  \t       <i class=\"fas fa-comment-dots\"></i>\r\n");
      out.write("  \t       <p class=\"food_post_like_count\">113</p>\r\n");
      out.write("  \t       <i class=\"fas fa-link\"></i>\r\n");
      out.write("  \t     </div>\r\n");
      out.write("  \t     <div class=\"content2\">\r\n");
      out.write("  \t       <i class=\"fas fa-map-marker-alt\"></i>\r\n");
      out.write("  \t       <!-- <p class=\"content2_name\">위치</p> -->\r\n");
      out.write("  \t       <div class=\"content2_address\">서울 강서구 양천로26길 10-6</div>\r\n");
      out.write("  \t     </div>\r\n");
      out.write("  \t     <div class=\"content3\">\r\n");
      out.write("  \t       <i class=\"fas fa-phone-alt\"></i>\r\n");
      out.write("  \t       <!-- <p class=\"content3_name\">연락처</p> -->\r\n");
      out.write("  \t       <div class=\"content3_pone\">02-1111-2222</div>\r\n");
      out.write("  \t     </div>\r\n");
      out.write("  \t     \r\n");
      out.write("<!--   \t     <div class=\"content4\">\r\n");
      out.write("  \t       <i class=\"far fa-clock\"></i>\r\n");
      out.write("  \t       <div class=\"content4_time\">매일 15:00 - 23:00</div>\r\n");
      out.write("  \t     </div>\r\n");
      out.write("  -->\r\n");
      out.write("  \t     \r\n");
      out.write("  \t     \r\n");
      out.write("  \t   </div>\r\n");
      out.write("  \t </div>\r\n");
      out.write("  \t <div class=\"food_post\"></div>\r\n");
      out.write("  \t <div class=\"food_post\"></div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("    <br><br>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <br><br>\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("<div id=\"aaa\">\r\n");
      out.write("  <div id=\"bbb\">asdfasdfasdfasdfasdfasdfasdf</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <h1>test</h1>\r\n");
      out.write("  <div class=\"font1\">Do Hyeon</div>\r\n");
      out.write("  <div class=\"font2\">Gothic A1</div>\r\n");
      out.write("  <div class=\"font3\">Indie Flower</div>\r\n");
      out.write("  <div class=\"font4\">Jua</div>\r\n");
      out.write("  <div class=\"font5\">Noto Sans KR header</div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"font7\">Roboto 잡다구리</div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"font6\">기본 잡다구리  더 많은 여행기 보기 </div>\r\n");
      out.write("  <div class=\"font8\">기본 잡다구리  더 많은 여행기 보기</div>\r\n");
      out.write("  <div class=\"font9\">기본 잡다구리  더 많은 여행기 보기</div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <br><br>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <br><br>\r\n");
      out.write("   -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!-- JQuery  -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<!-- Slick Carousel -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\t\t\r\n");
      out.write("<!-- main.jsp script -->\t\t\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/main.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('.img16').click(function(){\r\n");
      out.write("\tlocation.href=\"http://www.naver.com\";\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
